// G letter
function glorioso() {
    document.getElementById("song").innerHTML="<p><b>Glorioso</b><br>BJ Putnam - bpm: 148</p><hr><p>¡Gl<u><small>A</small></u>ori<u><small>E</small></u>os<u><small>F#m-D</small></u>o! Te cantamos<br>¡Gl<u><small>A</small></u>ori<u><small>E</small></u>os<u><small>F#m-D</small></u>o! Lo gritamos<br><u><small>A</small></u>Cristo te al<u><small>E</small></u>abaré<br><u><small>F#m</small></u>Tu nombre ex<u><small>D</small></u>altaré<br>¡Gl<u><small>A</small></u>ori<u><small>E</small></u>os<u><small>D</small></u>o! Nadie como tú</p><p><sub>Intro: D-F#m-D-A-E</sub></p><hr><p><u><small>D</small></u>Tú r<u><small>A</small></u>einar<u><small>E</small></u>ás<br>Por si<u><small>F#m</small></u>empre y siempre<br><u><small>D</small></u>Tú v<u><small>A</small></u>ivir<u><small>E</small></u>ás</p><p><u><small>D</small></u>Tu am<u><small>A</small></u>or ser<u><small>E</small></u>á<br>Por si<u><small>F#m</small></u>empre y siempre<br><u><small>D</small></u>No c<u><small>A</small></u>ambiar<u><small>E</small></u>ás</p><hr><p>Gritar<u><small>D</small></u>é, gritaré<br>Porque bu<u><small>A</small></u>eno es Dios<br>Cantar<u><small>E</small></u>é, cantaré<br>Tú eres <u><small>F#m</small></u>El Señor<br><u><small>D</small></u>Declarar<u><small>A</small></u>é, nadie c<u><small>E</small></u>omo tú</p><hr><p><u><small>A</small></u>Tu luz brillar<u><small>C#7</small></u>á, todos ver<u><small>F#m</small></u>án<br>No hay nadie c<u><small>D</small></u>omo tú</p>";
}
// T letter
    function tuguiasmidestino() {
       document.getElementById("song").innerHTML="<p><b>Tu guías mi destino</b><br>Josue del Cid - bpm:76</p><hr><p><sub>Intro: C-Am-G-F</sub></p><p><u><small>C</small></u>Tu guías mi dest<u><small>G</small></u>in<u><small>Am</small></u>o<br>Tu guías mis p<u><small>F</small></u>asos<br><u><small>C</small></u>En ti solo conf<u><small>G</small></u>ío<u><small>Am</small></u><br>Hoy vengo a tus br<u><small>F</small></u>azos</p><hr><p><u><small>G</small></u>No tengo a n<u><small>Am</small></u>adie mas que a t<u><small>F</small></u>i<br><u><small>G</small></u>Tu eres mi raz<u><small>Am</small></u>ón de viv<u><small>F</small></u>ir</p><hr><p>La fu<u><small>C</small></u>ente de mi vida eres tu<br>Mi am<u><small>Am</small></u>igo, mi consuelo eres tu<br><u><small>G</small></u>No tengo a nadie mas que a t<u><small>Dm7</small></u>i<br><u><small>F</small></u>Tu eres mi razón de viv<u><small>G</small></u>ir<br>Solo t<u><small>Intro</small></u>u</p><p><sub>Puente: F-C-G</sub></p>";
   }
// V letter
    function vieneya() {
        document.getElementById("song").innerHTML="<p><b>Viene ya</b><br>Miel San Marcos - bpm:150</p><hr><p><sub>Intro: Am-F-C-G</sub></p><p><u><small>Am</small></u>Prepar<u><small>F</small></u>emos el cam<u><small>C</small></u>ino Cristo vi<u><small>G</small></u>ene y<u><small>Am-F-C-G</small></u>a<br><u><small>Am</small></u>Anunci<u><small>F</small></u>emos su ven<u><small>C</small></u>ida en tod<u><small>G</small></u>o lug<u><small>Am-F-C-G</small></u>ar<br><u><small>Am</small></u>Que se <u><small>F</small></u>abran hoy las pu<u><small>C</small></u>ertas el v<u><small>G</small></u>iene y<u><small>Am-F-C-G</small></u>a<br><u><small>Am</small></u>Volver<u><small>F</small></u>emos a ador<u><small>C</small></u>arle por la eternid<u><small>G</small></u>ad</p><hr><p>Viene y<u><small>F</small></u>a mi am<u><small>C</small></u>ado, pr<u><small>G</small></u>onto le ver<u><small>Am</small></u>é<br>Viene y<u><small>F</small></u>a mi am<u><small>C</small></u>ado, pr<u><small>G</small></u>onto volver<u><small>Am</small></u>á</P><P>Voy cant<u><small>F</small></u>ando, grit<u><small>C</small></u>ando, celebr<u><small>G</small></u>ando su vict<u><small>Am</small></u>oria<br>Viene y<u><small>F</small></u>a mi am<u><small>C</small></u>ado, Cr<u><small>G</small></u>isto viene y<u><small>Am</small></u>a</p><hr><P><sub>Puente: Am-F-C-Am</sub></P><p>Volveremos, cantando<br>Volveremos, saltando<br>Volveremos, con gozo<br>Volveremos gritando</p><P><sub>Solo: F-C-G-Am</sub></P><hr><P>Voy cant<u><small>F</small></u>ando, grit<u><small>C</small></u>ando, celebr<u><small>G</small></u>ando su vict<u><small>Am</small></u>oria<br>Viene y<u><small>F</small></u>a mi am<u><small>C</small></u>ado, Cr<u><small>G</small></u>isto viene y<u><small>Am</small></u>a</p>";
    }
